version: "3.7"

services:
  vendas-db:
    image: postgres:15.3
    container_name: vendas-postgres    
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vendas-db
    volumes:
      - vendas-service-db:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - padrao
  
  rabbitmq:
    container_name: RabbitMQ
    hostname: rabbitmq
    build:
      context: ./rabbitmq
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672" #management
      - "5672:5672"   #amqp
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:15672 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - padrao

  vendas-service:
    container_name: vendas-service
    image: openjdk:17-alpine
    ports:
      - "8010:8080"
    environment:
      REGISTRY_PREFER_IP: 'true'
      APPLICATION_NAME: vendas-service
      SPRING_PROFILES_ACTIVE: 'prod'
    command: java -Duser.timezone=GMT-03:00 -Xmx256m -Xmx184m -jar /services/vendas-service.jar
    volumes:
      - ./../vendas-service/target/vendas-service.jar:/services/vendas-service.jar
    networks:
      - padrao
    links:
      - rabbitmq
      - vendas-db

networks:
  padrao:
    driver: bridge

volumes:
  rabbitmq_data_volume:
  vendas-service-db: