version: "3.7"

services:
  vendas-db:
    image: postgres:15.3
    container_name: vendas-postgres    
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vendas-db
    volumes:
      - vendas-service-db:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - padrao

  pagamentos-db:
    image: postgres:15.3
    container_name: pagamentos-postgres    
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pagamentos-db
    volumes:
      - pagamento-service-db:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    networks:
      - padrao
  
  rabbitmq:
    container_name: RabbitMQ
    hostname: rabbitmq
    build:
      context: ./rabbitmq
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672" #management
      - "5672:5672"   #amqp
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:15672 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - padrao

  vendas-service:
    container_name: vendas-service
    build:
      context: ./../vendas-service
    environment:
      REGISTRY_PREFER_IP: 'true'
      APPLICATION_NAME: vendas-service
      SPRING_PROFILES_ACTIVE: 'prod'
    ports:
      - "8010:8080"
    networks:
      - padrao
    links:
      - rabbitmq
      - vendas-db

  pagamento-service:
    container_name: pagamento-service
    build:
      context: ./../pagamento-service    
    environment:
      REGISTRY_PREFER_IP: 'true'
      APPLICATION_NAME: pagamento-service
      SPRING_PROFILES_ACTIVE: 'prod'
    ports:
      - "8020:8080"
    networks:
      - padrao
    links:
      - rabbitmq
      - pagamentos-db

networks:
  padrao:
    driver: bridge

volumes:
  rabbitmq_data_volume:
  vendas-service-db:
  pagamento-service-db: